import React from 'react';

import Head from 'next/head';

import LoginForm from '@/components/auth/login';
import Box from '@/components/common/Box';
import MainLayout from '@/layouts/MainLayout';

const index = () => {
  return (
    <>
      <Head>
        <title>Вход</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout scrollbarWrapper>
        {({ height }) => (
          <div
            className="flex h-full w-full justify-center p-3 pt-12 sm:items-center sm:pt-3"
            style={{ minHeight: height }}
          >
            <Box type="normal">
              <LoginForm />
            </Box>
          </div>
        )}
      </MainLayout>
    </>
  );
};

export default index;
