import React, { useEffect } from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';

import LoginForm from '@/components/auth/login';
import Box from '@/components/common/Box';
import MainLayout from '@/layouts/MainLayout';

const Login = () => {
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === 'authenticated') router.push('/');
  }, [router, status]);

  return (
    <>
      <Head>
        <title>Вход</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout scrollbarWrapper centerContent>
        <div className="flex h-full w-full justify-center p-3 pt-12 sm:items-center sm:pt-3">
          <Box type="normal">
            <LoginForm />
          </Box>
        </div>
      </MainLayout>
    </>
  );
};

export default Login;
