import { useEffect, useRef, useState } from 'react';

import { getCookie } from 'cookies-next';
import { NextApiRequest, NextApiResponse } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useSession } from 'next-auth/react';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import SimpleBar from 'simplebar-react';

import Button from '@/components/common/Button';
import Input from '@/components/common/Input';
import Modal from '@/components/common/Modal';
import Chat from '@/components/stream/Chat';
import NewChallengeForm from '@/components/stream/NewChallengeForm';
import Player from '@/components/stream/Player';
import StreamLayout from '@/layouts/StreamLayout';
import { classNames } from '@/utils/functions';

const Stream = () => {
  const [chosenFunc, setChosenFunc] = useState<'chat' | 'challenges'>('chat');
  const [showModal, setShowModal] = useState(false);
  const [showControls, setShowControls] = useState(false);
  const [mouseOver, setMouseOver] = useState(0);
  const { data: session } = useSession();
  const { query } = useRouter();
  const { name } = query;
  const { t } = useTranslation('stream');

  const timeoutRef = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    const disableControls = () => setShowControls(false);

    if (showControls) {
      if (timeoutRef.current && timeoutRef.current.refresh)
        timeoutRef.current.refresh();
      else timeoutRef.current = setTimeout(disableControls, 3000);
    }

    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, [showControls, mouseOver]);

  const getScreen = () => {
    if (name) {
      if (
        !session?.name ||
        (name as string).toLowerCase() !== session.name.toLowerCase()
      ) {
        return <Player showControls={showControls} />;
      } else if (
        (name as string).toLowerCase() === session?.name.toLowerCase()
      ) {
        return (
          <Button text={t('stream')} handleClick={() => setShowModal(true)} />
        );
      }
    }
  };

  return (
    <>
      <Head>
        <title>{`${name} - potok`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <StreamLayout>
        {({ mode, mdBP }) => (
          <div className="relative flex max-w-full grow flex-col md:flex-row">
            <div className="flex w-full flex-col border-white/40 md:border-r">
              <div
                className="relative flex aspect-video max-h-full items-center justify-center bg-black"
                onMouseMove={() => {
                  setShowControls(true);
                  setMouseOver((prevState) => ++prevState);
                }}
              >
                {getScreen()}
              </div>
            </div>
            <div className="flex grow flex-col md:w-80">
              <div className="flex h-10 md:hidden">
                <button
                  className={classNames(
                    'w-1/2 border border-white/40 py-2',
                    chosenFunc === 'challenges'
                      ? 'bg-[#7520A9]/40 text-chat'
                      : 'hover:bg-[#7520A9]/30'
                  )}
                  onClick={() => setChosenFunc('challenges')}
                >
                  {t('challenges')}
                </button>
                <button
                  className={classNames(
                    'w-1/2 border border-white/40 py-2',
                    chosenFunc === 'chat'
                      ? 'bg-[#7520A9]/40 text-chat'
                      : 'hover:bg-[#7520A9]/30'
                  )}
                  onClick={() => setChosenFunc('chat')}
                >
                  {t('chat')}
                </button>
              </div>
              {mdBP && chosenFunc === 'challenges' ? (
                <SimpleBar className="h-0 grow">
                  {mode === 'view' ? (
                    <p className="text-center">{t('empty')}</p>
                  ) : (
                    <NewChallengeForm />
                  )}
                </SimpleBar>
              ) : (
                <Chat />
              )}
            </div>
          </div>
        )}
      </StreamLayout>

      {showModal && (
        <Modal show={showModal} hide={() => setShowModal(false)}>
          <div className="flex flex-col gap-4">
            <h1 className="text-2xl font-bold">{t('stream')}</h1>
            <div className="flex flex-col gap-2">
              <p>Stream key:</p>
              <div className="flex gap-4">
                <button>
                  <Image
                    src="/images/refresh.svg"
                    alt="refresh"
                    width={32}
                    height={32}
                  />
                </button>
                <Input
                  inputAttributes={{ readOnly: true, value: 'aaaaaaaaaaa' }}
                  glow
                />
                <button onClick={() => navigator.clipboard.writeText('aa')}>
                  <Image
                    src="/images/copy.svg"
                    alt="copy"
                    width={32}
                    height={32}
                  />
                </button>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </>
  );
};

export default Stream;

export const getServerSideProps = async ({
  req,
  res
}: {
  req: NextApiRequest;
  res: NextApiResponse;
}) => {
  const locale = getCookie('locale', { req, res });

  return {
    props: {
      ...(await serverSideTranslations(locale?.toString() ?? 'ru', [
        'common',
        'stream',
        'streams',
        'new-challenge',
        'chat'
      ]))
    }
  };
};
