import { useState } from 'react';

import Head from 'next/head';

import Streams from '@/components/home/Streams';
import HomePageLayout from '@/layouts/HomePageLayout';
import { Categories, categories } from '@/utils/constants';

export default function Home() {
  const [category, setCategory] = useState<Categories>('all');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePageLayout
        curCategory={category}
        categories={categories}
        setCategory={setCategory}
      >
        <Streams />
      </HomePageLayout>
    </>
  );
}
